In [1]:
import torch
from torch import nn

torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1')


(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [2]:
torch.cuda.device_count()


1

In [3]:
def try_gpu(i=0):  #@save
    """如果存在，则返回gpu(i)，否则返回cpu()"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  #@save
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]"""
    devices = [torch.device(f'cuda:{i}')
             for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()


(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [14]:
x = torch.tensor([1, 2, 3])
x.device


device(type='cpu')

In [21]:
X = torch.ones(2, 3, device=try_gpu())
X


tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [18]:
Z = X.cuda(0)
print(X)
print(Z)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [20]:
Z.cuda(0) is Z



True

In [11]:
net[0].weight.data.device


device(type='cuda', index=0)