In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))


tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到构建更复杂的模型中

In [2]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()


tensor(-5.5879e-09, grad_fn=<MeanBackward0>)

带参数的图层

In [3]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
linear = MyLinear(5, 3)
linear.weight


Parameter containing:
tensor([[-1.3001, -1.9699, -2.1504],
        [-0.7308, -0.0265,  0.5929],
        [ 1.0600, -0.3370,  1.6379],
        [ 1.3811, -0.1286,  0.9242],
        [ 2.0181,  0.4950, -1.5146]], requires_grad=True)

使用自定义层直接执行前向传播计算。

In [4]:
linear(torch.rand(2, 5))


tensor([[0.0000, 0.0000, 0.0000],
        [0.8096, 0.0000, 0.5367]])

使用自定义层构建模型

In [5]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))


tensor([[0.],
        [0.]])